version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres_container
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  web:
    build:
      context: .
    volumes:
      - ./holiday_flat:/app/holiday_flat  # Mount project folder
    ports:
      - "8000:8000"
    command: gunicorn holiday_flat.wsgi.application --bind 0.0.0.0:8000
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}